

export const test13 = 'MONOMIAL IDEALS WITH QUASI-LINEAR QUOTIENTS\n' +
    'ANIQA AHMAD1, IMRAN ANWAR2, SHAHEEN NAZIR3,\n' +
    'Abstract. In this paper, we extend the notion of quasi-linear quotients for a\n' +
    'pure monomial ideal (not necessarily square-free) of degree d. We introduce\n' +
    'the notion of quasi-linear free resolution and show that if a pure monomial ideal\n' +
    'I= (u1; u2; : : : ; u m) of degree din the polynomial ring S=k[x1; : : : ; x n]\n' +
    'admits quasi-linear quotients then Lq= (u1; : : : ; u q1) :uqadmits quasi-linear\n' +
    'free resolution for all q¶m. Moreover, we show that if a pure monomial ideal\n' +
    'Iof degree dadmits quasi-linear quotients then I<t>will also have quasi-linear\n' +
    'quotients for t§d.\n' +
    'Key words :shellable simplicial complex, , facet ideal, graded free resolution,\n' +
    'graded betti numbers, betti diagram, colon of monomial ideals.\n' +
    '2000 Mathematics Subject Classi♀cation : Primary 13P10, Secondary 13H10, 13F20,\n' +
    '13C14.\n' +
    '1.Introduction\n' +
    'The class of square-free monomial ideals with quasi-linear quotients was intro-\n' +
    'duced in [1]. A monomial ideal is said to have quasi-linear quotients , if there exists\n' +
    'a minimal monomial system of generators u1;u2;:::;umofIsuch that♀01(Lk)6= 0\n' +
    'for all 1< k¶m, whereLk= (u1;u2;:::;uk1) : (uk):The concept of shellability\n' +
    'has been the subject of a considerable number of geometric and algebraic investiga-\n' +
    'tions for instance see [2], [3], [4], and [6]. The facet ideal IF(☺) (introduced in [5])of a\n' +
    'pure shellable simplicial complex ☺ admits quasi-linear quotients [2]. Moreover, the\n' +
    'class of monomial ideals with linear quotients (introduced by Herzog and Takayama\n' +
    '[7]) is contained in the class of monomial ideals with quasi-linear quotients.\n' +
    'The potential aim of this article is to study the monomial ideals with quasi-liner\n' +
    'quotients. We introduce the notion of quasi-linear free resolution and show that if a\n' +
    'pure monomial ideal I= (u1;u2;:::;um) of degree dadmits quasi-linear quotients\n' +
    'thenLq= (u1;:::;uq1) :uqadmits quasi-linear free resolution for allq¶m. We\n' +
    'also show that if a pure monomial ideal Iof degreedadmits quasi-linear quotients\n' +
    'thenI<t>will also have quasi-linear quotients for t§d.\n' +
    'Acknowledgments: The authors would like to thank the Higher Education\n' +
    'Commission, Pakistan for supporting this research under the project number 4234.\n' +
    '1.COMSATS Institute of Information Technology Lahore, Pakistan.\n' +
    '2.Abdus Salam School of Mathematical Sciences, GC University, Lahore, Pakistan.\n' +
    '3.Lahore University of Management Sciences, Pakistan.\n' +
    '12.Background\n' +
    'In this section, we de♀ne some basic notions that we will use in the paper along\n' +
    'with some background theory.\n' +
    'LetS=k[x1;:::;xn] denote the polynomial ring in nvariables over an in♀nite ♀eld\n' +
    'kwith each deg( xi) = 1 andIa monomial ideal of S. The graded Betti numbers\n' +
    '♀i;j=♀i;j(I) appear in the graded minimal free resolution\n' +
    'F: 0!M\n' +
    'j2ZS(j)♀h;j!☺☺☺!M\n' +
    'j2ZS(j)♀0;j!I\n' +
    'ofIinS. Then♀i;j(I) = dimkTori(I;k)jfor alliandj. There are two important\n' +
    'invariants attached to a monomial ideal I→Sde♀ned in terms of the minimal\n' +
    'graded free resolution of I:\n' +
    'proj dim(I) = maxfi:♀i;j(I)6= 0g;\n' +
    'reg(I) = maxfj:♀i;i+j(I)6= 0 for some ig\n' +
    'namely projective dimension andregularity ofIrespectively. We say that Ihas a\n' +
    'linear resolution if there exists an integer m§1 such that ♀i;i+j= 0 for alliand\n' +
    'jwithj6=m. Thus, in particular, if Ihas a linear resolution, then Iis generated\n' +
    'by homogeneous polynomials of the same degree.\n' +
    'De♀nition 2.1. LetIbe a monomial ideal in Sandube any monomial in S. Then\n' +
    'thecolon ideal ofIwith respect to ( u) is de♀ned as\n' +
    'I: (u) =ff2Sjfu2Ig:\n' +
    'Here, we recall an important class of monomial ideals namely ideals with linear\n' +
    'quotients along with some important results.\n' +
    'De♀nition 2.2. LetI→S=k[x1;:::;xn] be a monomial ideal, we say that\n' +
    'Ihaslinear quotients , if there exists a minimal monomial system of generators\n' +
    'u1;u2;:::;umofIsuch thatLkis generated by linear forms for all 1 < k¶m,\n' +
    'where\n' +
    'Lk= (u1;u2;:::;uk1) : (uk):\n' +
    'Moreover for each k, we denote the number of generators of Lkbyrkor in other\n' +
    'words▬(Lk) =rk.\n' +
    'One of the reasons that makes ideals with linear quotient an important subject\n' +
    'for considerations is due to the following result [6, Proposition 8.2.1].\n' +
    'Theorem 2.3. Suppose that I→Sis a graded ideal generated in degree dand that\n' +
    'Ihas linear quotients. Then Ihas ad-linear resolution.\n' +
    '3.pure monomial ideals with quasi-linear quotients\n' +
    'In this section, we will consider only monomial ideals with quasi-linear quotients\n' +
    'in the polynomial ring S=k[x1;:::;xn]. We say that a monomial ideal I→Sis\n' +
    'pure of degree d, if and only if ♀0;j(I) = 0 for all j6=d:\n' +
    '2De♀nition 3.1. LetIbe a monomial ideal in S. We de♀ne the indeg( I) as follows\n' +
    'indeg(I) = minfj:♀0;j(I)6= 0g:\n' +
    'De♀nition 3.2. LetI→Sbe a monomial ideal, we say that Ihasquasi-linear\n' +
    'quotients , if there exists a minimal monomial system of generators u1;u2;:::;umof\n' +
    'Isuch that indeg( Li) = 1 for all 1 <i¶m, where\n' +
    'Li= (u1;u2;:::;ui1) : (ui):\n' +
    'Remark 3.3. LetI→Sbe a monomial ideal having linear quotients , thenI\n' +
    'hasquasi-linear quotients as well. Therefore, the class of ideals with quasi-linear\n' +
    'quotients is a generalization of the class of monomial ideals with linear quotients.\n' +
    'De♀nition 3.4. We say that Ihas a quasi-linear resolution if for each integer i\n' +
    'with 0¶i <proj dim(I), there exists an integer jsuch that,♀i;j(I)6= 0 implies\n' +
    '♀i+1;j+1(I)6= 0. Thus, in particular, if Iwill have a quasi-linear resolution, then\n' +
    'there is at least one linear shift in each step of the minimal free resolution of I.\n' +
    'The following example is given to show the various aspects of quasi-linear\n' +
    'resolution of an ideal I.\n' +
    'Example 3.5. Let us consider the polynomial ring S=k[x1;:::;x 7] and monomial\n' +
    'idealI= (x1x2x3;x1x3x4;x3x4x5;x4x5x6;x5x6x7):Its minimal free resolution is as\n' +
    'follows:\n' +
    '0!S(7)!S(4)S(6)!S(3)5!I\n' +
    'with Betti diagram:\n' +
    '0 1 2\n' +
    '0 0 0 0\n' +
    '1 0 0 0\n' +
    '2 0 0 0\n' +
    '3 5 4 0\n' +
    '4 0 0 0\n' +
    '5 0 1 1\n' +
    'One can see the linear shift in each step clearly.\n' +
    'Theorem 3.6. LetI→S=k[x1;:::;xn] be a pure monomial ideal of degree\n' +
    'd, minimally generated by fu1;u2;:::;umg. IfIhas quasi-linear quotients, then\n' +
    'Lq= (u1;u2;:::;uq1) :uqhas a quasi-linear free resolution for all 1 <q¶m.\n' +
    'Proof. SinceIhas quasi-linear quotients, so Lqhas a variable as a generator, for all\n' +
    '1<q¶m. To showLqhas a quasi-linear free resolution, it is enough to show that\n' +
    'a monomial ideal containing a variable has a quasi-linear free resolution.\n' +
    'LetLbe an ideal containing a variable. We may assume that L= (J;x 1) with\n' +
    'x1=2supp(J). By using the de♀nition of minimal graded free resolution, one may\n' +
    'obtain a minimal graded free resolution of Lfrom a minimal graded free resolution\n' +
    'ofJ, as\n' +
    'TorS\n' +
    'i(L;k)j= TorS\n' +
    'i(J;k)TorS\n' +
    'i1(J(1);k)j;for alli§1 and\n' +
    'TorS\n' +
    '0(L;k)j= TorS\n' +
    '0((x1;k)TorS\n' +
    '0(J;k)j:\n' +
    '3Now suppose that ♀i+1(L)6= 0:Then♀i(J)6= 0:(In fact, if ♀i(J) = 0, then\n' +
    '♀i+1(J) = 0, which implies ♀i+1(L) = 0, a contradiction.) In particular, there exists\n' +
    'jsuch that♀i;j(J)6= 0. The presence of TorS\n' +
    'i(J;k)TorS\n' +
    'i1(J(1);k)jensures that\n' +
    '♀i;j(L)6= 0 and♀i+1;j+1(L)6= 0. Therefore, Lhas a quasi-linear free resolution for\n' +
    'allk¶m.\n' +
    'Here we give an example to demonstrate the step recursively mentioned in the\n' +
    'proof of above theorem.\n' +
    'Example 3.7. LetI= (a;b;cd;ce;de ) be a monomial ideal in the polynomial ring\n' +
    'S=k[a;b;c;d;e ]. Therefore, we have the following chain of ideals\n' +
    'I0= (cd;ce;de )→I1= (a;I 0)→I2=I\n' +
    'The Betti diagram of I0is given as:\n' +
    '0 1\n' +
    '0 0 0\n' +
    '1 0 0\n' +
    '2 3 2\n' +
    'The Betti diagram of I1can be obtained from I0(changes in shift are shown in bold\n' +
    'entries):\n' +
    '0 1 2\n' +
    '0 0 0 0\n' +
    '11 0 0\n' +
    '2 3 5 = 3+ 2 2 = 2+ 0\n' +
    'The Betti diagram of I2=Ican be obtained from I1(changes in shift are shown in\n' +
    'bold entries):\n' +
    ' 0 1 2 3\n' +
    '0 0 0 0 0\n' +
    '11+ 1 1 = 1 + 0 0 0\n' +
    '2 3 8 = 3+ 5 7 = 5+ 2 2 = 2+ 0\n' +
    'One can notice the changes in the shifts by comparing the above Betti diagrams.\n' +
    'It is clear from above that\n' +
    'TorS\n' +
    'i(I1;k)j= TorS\n' +
    'i(I0;k)TorS\n' +
    'i1(I0(1);k)jfori>0\n' +
    'and\n' +
    'TorS\n' +
    'i(I;k)j=TorS\n' +
    'i(I1;k)TorS\n' +
    'i1(I1(1);k)jfori>0:\n' +
    'Moreover,\n' +
    'TorS\n' +
    '0(I1;k)j= TorS\n' +
    '0((a);k)TorS\n' +
    '0(I0;k)j\n' +
    'and\n' +
    'TorS\n' +
    '0(I;k)j=TorS\n' +
    '0((b);k)TorS\n' +
    '0(I1;k)j:\n' +
    'For a pure monomial ideal I→Sof degreed, we haveI<t>is a monomial ideal\n' +
    'generated by tdegree monomials in I. In particular, I<t>=I:(x1;x2;:::;xn)td.\n' +
    '[3] Dress, A.,(1993). A new algebraic criterion for shellability, Beitr. Algebr. Geom. 340:1, 45-50.\n' +
    '[4] Eagon, J. A., Reiner, V.,(1998). Resolution of Stanley-Reisner Rings and Alexander Duality,\n' +
    'J. Pure Appl. Algebra 130(3), 265-275.\n' +
    '[5] Faridi, S.,(2002). The facet ideal of a simplicial complex, Manuscripta Mathematica , 109, 159-\n' +
    '174.\n' +
    '[6] Herzog, J., Hibi, T.,(2010). Monomial Algebra, 260 ;Springer, London.\n' +
    '[7] Herzog, J., Takayama, Y.,(2002) Resolutions by mapping cones, Homology Homotopy Appl. 4,\n' +
    'no. 2, 277294.\n' +
    'E-mail address :imrananwar@sms.edu.pk, aniqa.mathematics@gmail.com, shaheen.nazir@lums.edu.pk\n' +
    '5\n'

export const test35 = 'Initial-Boundary Value Problem for Hyperbolic Equation\n' +
    'with Singular Coe ﬃcient and Integral Condition of Second Kind\n' +
    'K. B. Sabitov1,*and N. V. Zaitseva2,**\n' +
    '(Submitted by A.M. Elizarov)\n' +
    '1Sterlitamak Branch of the Bashkir State University, pr. Lenina 49, Sterlitamak, Bashkortostan, 453103\n' +
    'Russia\n' +
    '2N. I. Lobachevskii Institute of Mathematics and Mechanics, Kazan (Volga Region) Federal University,\n' +
    'Kremlevskaya ul. 18, Kazan, Tatarstan, 420008 Russia\n' +
    'Received January 23, 2018\n' +
    'Abstract ▬We research an initial-boundary value problem with integral condition of the second kind\n' +
    'in a rectangular domain for a hyperbolic equation with singular coe ﬃcient. The solution is obtained\n' +
    'in the form of the Fourier §Bessel series. There are proved theorems on uniqueness, existence and\n' +
    'stability of the solution. In order to prove the existence of solution of the non-local problem we obtain\n' +
    'suﬃcient conditions for the convergence of the series in terms of the initial values.\n' +
    '2010 Mathematical Subject Classi ∟cation: 35L15,35L80\n' +
    'Keywords and phrases: hyperbolic equation, singular coe ﬃcient, non-local integral condition,\n' +
    'uniqueness, Fourier §Bessel series, existence, stability.\n' +
    '1. INTRODUCTION\n' +
    'Letl;T > 0be given real values, D=f(x;t)j0<x<l; 0<t<T gis rectangular domain. We\n' +
    'consider hyperbolic equation\n' +
    '2Bu(x;t)◄uttuxxk\n' +
    'xux= 0; (1)\n' +
    'wherek̸= 0is given real number. Equation (1) belongs to the class of degenerated hyperbolic equations.\n' +
    'Investigation of boundary value problems for that equations is of importance for contemporary theory\n' +
    'of diﬀerential equations with partial derivatives. The problems have numerous applications in gas\n' +
    'dynamics, magnet hydrodynamics, envelope theory and other ∟elds of science and technique.\n' +
    'The Cauchy and Cauchy §Goursat problems for equation (1) were studied ∟rst in the work [1] for\n' +
    'allk§1in characteristic triangle. As shown in the paper [2], the problems are not well-posed for\n' +
    'k< 0. And the papers [3, 4] contain studies of the problems for equations of mixed type such that\n' +
    'their hyperbolic parts coincide with equation (1). The non-local problems for equation (1) with integral\n' +
    'conditions of the ∟rst kind and second kind are studied in the papers [5 §7].\n' +
    'In the present paper we investigate the following initial-boundary value problem for equation (1)\n' +
    'in domainDwith non-local integral condition of the second kind for k¶  1. We put in the further\n' +
    'consideration without loss of generality l= 1, because equation (1) is invariant with regard to change of\n' +
    'variablesx1=x=l,y1=y=l.\n' +
    'Statement of the problem . It is necessary to ∟nd the function u(x;t)satisfying the following\n' +
    'restrictions:\n' +
    'u(x;t)2C1(D)\\C2(D); (2)\n' +
    '*E-mail: sabitov_fmf@mail.ru\n' +
    '**E-mail: n.v.zaiceva@yandex.ru2 SABITOV , ZAITSEVA\n' +
    '2Bu(x;t)◄0;(x;t)2D; (3)\n' +
    'u(x;0) =φ(x); u t(x;0) = (x);0¶x¶1; (4)\n' +
    'u(0;t) = 0;0¶t¶T; (5)\n' +
    '(\n' +
    'xk1u(x;t))′\n' +
    'x♀♀♀\n' +
    'x=1+1∫\n' +
    '0u(x;t)xdx = 0;0¶t¶T; (6)\n' +
    'whereφ(x), (x)are given su ﬃciently smooth functions satisfying matching conditions\n' +
    '(\n' +
    'xk1φ(x))′\n' +
    'x♀♀♀\n' +
    'x=1+1∫\n' +
    '0φ(x)xdx = 0;(\n' +
    'xk1 (x))′\n' +
    'x♀♀♀\n' +
    'x=1+1∫\n' +
    '0 (x)xdx = 0: (7)\n' +
    'The problems for di ﬀerential equations, where instead of classical initial and boundary value con-\n' +
    'ditions are given conditions connecting meanings of desired functions or its derivatives at inner and\n' +
    'boundary points of domains, arise in numerous branches of sciences: physics, chemistry, biology. In\n' +
    'particular, the problems with integral conditions are encountered in mathematical modeling of the\n' +
    'thermal conductivity, the transfer of moisture in capillary-porous media, processes in turbulent plasma.\n' +
    'The detailed study of boundary value problems with integral conditions for hyperbolic equations can\n' +
    'be found in the works [8 §10]. The papers [11 §13] contain investigations of problems with integral\n' +
    'conditions for equations with singular coe ﬃcient.\n' +
    'The condition (6) contains besides an integral operator the boundary meanings of derivative of the\n' +
    'desired function. According [8], we refer this integral condition to the second kind.\n' +
    'In what follows we apply the spectral analysis in proving of uniqueness, existence and stability of the\n' +
    'solution. It is built explicitly as the Fourier §Bessel series. We check its convergence in the class of\n' +
    'regular solutions.\n' +
    '2. UNIQUENESS\n' +
    'We seek particular solutions of equation (1), which do not vanish in domain Dand satisfy restrictions\n' +
    '(2), (5) and (6) in the form of products u(x;t) =X(x)T(t). We substitute the product into equation (1),\n' +
    'conditions (5) and (6), and obtain the following spectral problem for unknown function X(x):\n' +
    'X′′(x) +k\n' +
    'xX′(x) +§2X(x) = 0;0<x< 1; (8)\n' +
    'X(0) = 0; (9)\n' +
    '(\n' +
    'xk1X(x))′\n' +
    'x♀♀♀\n' +
    'x=1+1∫\n' +
    '0X(x)xdx = 0; (10)\n' +
    'here§2is the separation constant. By virtue of equation (8) and condition (9) we obtain from integral\n' +
    'condition (10):\n' +
    '(\n' +
    'xk1X(x))′\n' +
    'x♀♀♀\n' +
    'x=1+1∫\n' +
    '0X(x)xdx = (k1)X(1) +X′(1)1\n' +
    '§21∫\n' +
    '0[\n' +
    'xX′′(x) +kX′(x)]\n' +
    'dx\n' +
    '= (k1)X(1) +X′(1)1\n' +
    '§21∫\n' +
    '0@\n' +
    '@x[\n' +
    'xX′(x) + (k1)X(x)]\n' +
    'dx\n' +
    'LOBACHEVSKII JOURNAL OF MATHEMATICSINITIAL-BOUNDARY VALUE PROBLEM 3\n' +
    '= (k1)X(1) +X′(1)1\n' +
    '§2[\n' +
    'xX′(x) + (k1)X(x)]♀♀♀1\n' +
    '0=(\n' +
    '11\n' +
    '§2)\n' +
    '(X′(1) + (k1)X(1)) = 0:\n' +
    'We obtain§2= 1orX′(1) + (k1)X(1) = 0 . Hence, the non-local condition (10) is equivalent to\n' +
    'two local conditions. Apparently, this is inherent only in the equation (1).\n' +
    'The general solution of equation (8) for k¶  1is determined by formula\n' +
    'eX(x) =K1x↨J↨(§x) +K2x↨Y↨(§x);\n' +
    'whereJ↨(↑),Y↨(↑)are Bessel functions of the ∟rst and the second kinds of order ↨= (1k)=2relatively,\n' +
    'andK1,K2are arbitrary constants. The common decision for K1= 1,K2= 0satis∟es condition (9).\n' +
    'As a result, we obtain eX(x) =x↨J↨(§x),↨= (1k)=2.\n' +
    'Then eigenvalue §2\n' +
    '0= 1corresponds to eigenfunction X0(x) =x↨J↨(§0x). We substitute this\n' +
    'decision into condition of the third kind. And deduce the following equation for the eigenvalues of\n' +
    'problem (8) §(10):\n' +
    '§J′\n' +
    '↨(§)↨J↨(§) = 0: (11)\n' +
    'By virtue of formula zJ′\n' +
    '↨(z)↨J↨(z) =zJ↨+1(z)see [14] (p. 305) equation (11) is equivalent to the\n' +
    'following one: J3k\n' +
    '2(§) = 0 . According [15] (p. 317), the zeros of this equation have asymptotic formula\n' +
    '§n=↓n+↓=2k↓=4 +O(1=n) (12)\n' +
    'for suﬃciently large n. Thus, the problem (8) §(10) has the following system of eigenfunctions\n' +
    'eX0(x) =x1k\n' +
    '2J1k\n' +
    '2(§0x);eXn(x) =x1k\n' +
    '2J1k\n' +
    '2(§nx); n2N;\n' +
    'and its eigenvalues §nare zeros of equation (11). The obtained system of eigenfunctions is not\n' +
    'orthogonal on segment [0, 1], because the eigenvalue §0is not zero of Bessel function J3k\n' +
    '2(§x), i.e.,\n' +
    'it is not root of equation (11). But the subsystem of functions eXn(x),n2N, is orthogonal and complete\n' +
    'in the space L2[0;1]with weight xkas system of eigenfunctions of spectral problem (8), (9) and (11).\n' +
    'The orthogonality follows from equality\n' +
    '1∫\n' +
    '0xkeXn(x)eXm(x)dx=1∫\n' +
    '0xJ1k\n' +
    '2(§nx)J1k\n' +
    '2(§mx)dx= 0;\n' +
    'since§nand§mare the zeros of equation (11) and ↨= (1k)=2>1. This system is complete in\n' +
    'the spaceL2[0;1]by virtue of the Steklov theorem [14] (p. 314). Therefore, in what follows we consider\n' +
    'the orthonormalized system of eigenfunctions eXn(x),n= 1;2;:::. The equations eXn(x)enable us to\n' +
    'consider below the following normalized orthogonal system of eigenfunctions\n' +
    'Xn(x) =eXn(x)\n' +
    'jjeXnjjL2;→(0;1); (13)\n' +
    'the norm is de ∟ned by formula\n' +
    'jjeXnjj2\n' +
    'L2;→(0;1)=1∫\n' +
    '0→(x)eX2\n' +
    'n(x)dx; → (x) =xk:\n' +
    'According [16], we introduce functions\n' +
    'un(t) =1∫\n' +
    '0u(x;t)xkXn(x)dx; n = 1;2;:::; (14)\n' +
    'LOBACHEVSKII JOURNAL OF MATHEMATICS4 SABITOV , ZAITSEVA\n' +
    'and auxiliary functions\n' +
    'un;"(t) =1"∫\n' +
    '"u(x;t)xkXn(x)dx; n = 1;2;:::;\n' +
    'where"> 0is suﬃciently small. We di ﬀerentiate this equality twice with regard to variable t,0<t<T ,\n' +
    'and obtain by means of equation (1)\n' +
    'u′′\n' +
    'n;"(t) =1"∫\n' +
    '"utt(x;t)xkXn(x)dx=1"∫\n' +
    '"(\n' +
    'uxx+k\n' +
    'xux)\n' +
    'xkXn(x)dx\n' +
    '=1"∫\n' +
    '"@\n' +
    '@x(xkux)Xn(x)dx=xkuxXn(x)♀♀♀1"\n' +
    '"1"∫\n' +
    '"xkuxX′\n' +
    'n(x)dx:\n' +
    'In addition, we obtain from this equality by virtue of equation (8):\n' +
    '1"∫\n' +
    '"xkuxX′\n' +
    'n(x)dx=§2\n' +
    'nun;"(t) +u(x;t)xkX′\n' +
    'n(x)♀♀♀1"\n' +
    '":\n' +
    'The last two equalities imply\n' +
    'u′′\n' +
    'n;"(t) =xkuxXn(x)♀♀♀1"\n' +
    '"§2\n' +
    'nun;"(t)u(x;t)xkX′\n' +
    'n(x)♀♀♀1"\n' +
    '":\n' +
    'It follows from formula eXn(x)thatXn(x) =O(x1k)andX′\n' +
    'n(x) =O(xk)forx!0. Then we pass in\n' +
    'the last equality to limit for "!0, and obtain by means of conditions (2), (5), (9), (11):\n' +
    'u′′\n' +
    'n(t) +§2\n' +
    'nun(t) = [ux(1;t) + (k1)u(1;t)]Xn(1); t2(0;T): (15)\n' +
    'Then we multiply equation (1) by xand integrate the product for ∟xedt2(0;T)with regard to variable\n' +
    'xfrom"to1". As a result, we obtain\n' +
    'd2\n' +
    'dt21"∫\n' +
    '"u(x;t)xdx[xux+ (k1)u]♀♀♀1"\n' +
    '"= 0:\n' +
    'In the obtained equality we pass to the limit for "!0, and by virtue of conditions (2), (5), (6) conclude\n' +
    'that\n' +
    'd2\n' +
    'dt2[(\n' +
    'xk1u(x;t))′\n' +
    'x♀♀♀♀\n' +
    'x=l]\n' +
    '[lux(l;t) + (k1)u(l;t)] = 0:\n' +
    'Consequently,\n' +
    'd2\n' +
    'dt2[ux(1;t) + (k1)u(1;t)] + [ux(1;t) + (k1)u(1;t)] = 0:\n' +
    'We denoteZ(t) =ux(1;t) + (k1)u(1;t), and obtain ordinary di ﬀerential equation Z′′(t) +Z(t) = 0 .\n' +
    'Its general solution is\n' +
    'Z(t) =P1cost+P2sint;\n' +
    'whereP1andP2are arbitrary constants. Consequently,\n' +
    'ux(1;t) + (k1)u(1;t) =P1cost+P2sint:\n' +
    'The initial conditions (4) enable us to ∟nd meanings of the constants from the last equality:\n' +
    'P1=φ′(1) + (k1)φ(1); P 2= ′(1) + (k1) (1):\n' +
    'LOBACHEVSKII JOURNAL OF MATHEMATICSINITIAL-BOUNDARY VALUE PROBLEM 5\n' +
    'Thus,\n' +
    'ux(1;t) + (k1)u(1;t) =[\n' +
    'φ′(1) + (k1)φ(1)]\n' +
    'cost+[\n' +
    ' ′(1) + (k1) (1)]\n' +
    'sint:\n' +
    'We substitute the last equality into (15), and obtain the following equation for determination of functions\n' +
    'un(t):u′′\n' +
    'n(t) +§2\n' +
    'nun(t) =P3cost+P4sint,t2(0;T), where\n' +
    'P3=P1Xn(1) = (φ′(1) + (k1)φ(1))J1k\n' +
    '2(§n); P 4=P2Xn(1) = ( ′(1) + (k1) (1))J1k\n' +
    '2(§n):\n' +
    'The general solution of this ordinary equation is\n' +
    'un(t) =ancos§nt+bnsin§nt+vn(t); (16)\n' +
    'whereanandbnare arbitrary constants, vn(t)is determined by formula\n' +
    'vn(t) =1\n' +
    '§2n1[\n' +
    '(φ′(1) + (k1)φ(1)) cost+ ( ′(1) + (k1) (1)) sint]\n' +
    'J1k\n' +
    '2(§n):\n' +
    'Note that§2\n' +
    'n̸= 1for anyn2N, because ♠1are not zeros of equation (11).\n' +
    'In order to determine the coe ﬃcientsanandbnin (14) we use the initial conditions (4):\n' +
    'un(0) =1∫\n' +
    '0φ(x)xkXn(x)dx=φn; u′\n' +
    'n(0) =1∫\n' +
    '0 (x)xkXn(x)dx= n:\n' +
    'As a result, we obtain the system\n' +
    'an=φn1\n' +
    '§2n1(φ′(1) + (k1)φ(1))J1k\n' +
    '2(§n);\n' +
    'bn= n\n' +
    '§n1\n' +
    '(§2n1)§n( ′(1) + (k1) (1))J1k\n' +
    '2(§n):\n' +
    'We substitute these meanings of constants anandbninto (16), and ∟nd∟nally\n' +
    'un(t) =φncos§nt+ n\n' +
    '§nsin§nt+1\n' +
    '§2n1[\n' +
    'φ′(1) + (k1)φ(1)]\n' +
    'J1k\n' +
    '2(§n) (costcos§nt)\n' +
    '+1\n' +
    '(§2n1)§n[\n' +
    ' ′(1) + (k1) (1)]\n' +
    'J1k\n' +
    '2(§n)(\n' +
    'sint1\n' +
    '§nsin§nt)\n' +
    ': (17)\n' +
    'Theorem 1. If the problem (2) §(7) has a solution, then it is unique.\n' +
    'Proof. Letu(x;t)be a solution of homogeneous problem (2) §(6), whereφ(x)◄0and (x)◄0. We\n' +
    'multiply the equation (1) by x, and integrate it for ∟xedt2(0;T)in variablexfrom"up to 1". As a\n' +
    'result, we obtain\n' +
    '1"∫\n' +
    '"uttxdx1"∫\n' +
    '"(xuxx+kux)dx= 0 ord2\n' +
    'dt21"∫\n' +
    '"u(x;t)xdx1"∫\n' +
    '"@\n' +
    '@x(xux+ (k1)u)dx= 0:\n' +
    'We have from this\n' +
    'd2\n' +
    'dt21"∫\n' +
    '"u(x;t)xdx(xux+ (k1)u)♀♀♀1"\n' +
    '"= 0:\n' +
    'By virtue of conditions (2) and (5) we are able to pass in the last equality to the limit for "!0, and obtain\n' +
    'd2\n' +
    'dt21"∫\n' +
    '"u(x;t)xdx(ux(1;t) + (k1)u(1;t)) = 0;0¶t¶T:\n' +
    'LOBACHEVSKII JOURNAL OF MATHEMATICS6 SABITOV , ZAITSEVA\n' +
    'We∟nd from the integral condition (6):\n' +
    'ux(1;t) + (k1)u(1;t) =1∫\n' +
    '0u(x;t)xdx:\n' +
    'The substitution of this expression into previous equality leads to ordinary di ﬀerential equation\n' +
    'd2\n' +
    'dt21∫\n' +
    '0u(x;t)xdx +1∫\n' +
    '0u(x;t)xdx = 0;\n' +
    'whose general solution is1∫\n' +
    '0u(x;t)xdx =M1cost+M2sint, whereM1andM2are arbitrary con-\n' +
    'stants. We have from this by means of null initial conditions1∫\n' +
    '0u(x;t)xdx = 0.\n' +
    'Then from condition (6) we obtain ux(1;t) + (k1)u(1;t) = 0;0¶t¶T:Thus, for function u(x;t)\n' +
    'we obtain homogeneous boundary condition\n' +
    'u(0;t) = 0; u x(1;t) + (k1)u(1;t) = 0;0¶t¶T:\n' +
    'This problem is studied above by means of method of separation of variables, i.e., we have constructed\n' +
    'the system of eigenvalues (13), and by means of this system and the introduced functions (14) we ∟nd\n' +
    'their explicit form (17). By assumptions we have φ(x) = (x)◄0, then imply that φn= n◄0for\n' +
    'alln2N. We deduce from (17) that un(t) = 0 for alln2N. Then for any t2[0;T]relation (14)\n' +
    'implies that1∫\n' +
    '0u(x;t)xkXn(x)dx= 0. System (13) is complete in the space L2[0;1]with weight xk;\n' +
    'hence,u(x;t) = 0 almost everywhere on segment [0;1]for anyt2[0;T]. According (2), we obtain\n' +
    'u(x;t)2C(D). Consequently, u(x;t)◄0inD.\n' +
    '3. EXISTENCE\n' +
    'The obtained above particular solutions (13) and (17) enable us to write a solution of problem (2) §(7)\n' +
    'as the series\n' +
    'u(x;t) =1∑\n' +
    'n=1un(t)Xn(x): (18)\n' +
    'We assume that its term-by-term di ﬀerentiation is possible, and consider the following series:\n' +
    'ut(x;t) =1∑\n' +
    'n=1u′\n' +
    'n(t)Xn(x); ux(x;t) =1∑\n' +
    'n=1un(t)X′\n' +
    'n(x);\n' +
    'utt(x;t) =1∑\n' +
    'n=1u′′\n' +
    'n(t)Xn(x); uxx(x;t) =1∑\n' +
    'n=1un(t)X′′\n' +
    'n(x):\n' +
    'Let us show that under certain restrictions on functions φ(x)and (x)(see the initial conditions (4))\n' +
    'these series uniformly converge in closed domain D.\n' +
    'Lemma 1. For su ﬃciently large nand anyt2[0;T]there are valid bounds:\n' +
    'jun(t)j ¶C1(\n' +
    'jφnj+j nj\n' +
    'n)\n' +
    '+jφ′(1)j\n' +
    'n3=2+j ′(1)j\n' +
    'n3=2+jφ(1)j\n' +
    'n3=2+j (1)j\n' +
    'n3=2;\n' +
    'LOBACHEVSKII JOURNAL OF MATHEMATICSINITIAL-BOUNDARY VALUE PROBLEM 7\n' +
    'ju′\n' +
    'n(t)j ¶C2(njφnj+j nj) +jφ′(1)j\n' +
    'n1=2+j ′(1)j\n' +
    'n3=2+jφ(1)j\n' +
    'n1=2+j (1)j\n' +
    'n3=2;\n' +
    'ju′′\n' +
    'n(t)j ¶C3(\n' +
    'n2jφnj+nj nj)\n' +
    '+n1=2jφ′(1)j+j ′(1)j\n' +
    'n1=2+n1=2jφ(1)j+j (1)j\n' +
    'n1=2:\n' +
    'Here and in what follows Cistands for a positive constant.\n' +
    'Proof. Proof of the bounds follows from formulas (17) and (12).\n' +
    'Lemma 2. For su ﬃciently large nand anyx2[0;1]there are valid bounds:\n' +
    'jXn(x)j ¶C4;jX′\n' +
    'n(x)j ¶C5n;jX′′\n' +
    'n(x)j ¶C6n2:\n' +
    'Proof. As known,eXn(x) =x1k\n' +
    '2J1k\n' +
    '2(§nx)2C2[0;1], and for large ↑there is valid asymptotical\n' +
    'boundJ↨(↑) =O(\n' +
    '↑1=2)\n' +
    '. We∟nd\n' +
    'jjeXnjj2\n' +
    'L2;→(0;1)=1∫\n' +
    '0xkeX2\n' +
    'n(§nx)dx=1∫\n' +
    '0xJ2\n' +
    '1k\n' +
    '2(§nx)dx=1\n' +
    '2J2\n' +
    '3k\n' +
    '2(§n):\n' +
    'The relations (13) imply the ∟rst bound from this lemma. We evaluate derivatives of function eXn(x):\n' +
    'eX′\n' +
    'n(x) =§nx1k\n' +
    '2Jk+1\n' +
    '2(§nx);eX′′\n' +
    'n(x) =k\n' +
    'xeX′\n' +
    'n(x)§2\n' +
    'neXn(x):\n' +
    'From these equalities the remaining estimates follow.\n' +
    'Lemma 3. If functionφ(x)belongs toC2[0;1]and has third derivative φ′′′(x)with∟nite variation\n' +
    'on[0;1], then function  (x)belongs to C1[0;1]and has second derivative  ′′(x)with∟nite\n' +
    'variation on [0;1]. If\n' +
    'φ(0) = (0) =φ(1) = (1) =φ′(0) = ′(0) =φ′(1) = ′(1) =φ′′(0) =φ′′(1) = 0;\n' +
    'then\n' +
    'jφnj ¶C7n4;j nj ¶C8n3: (19)\n' +
    'Proof. We obtain by means of (8) and conditions of the lemma\n' +
    'φn=1∫\n' +
    '0φ(x)xkXn(x)dx=1\n' +
    '§2n1∫\n' +
    '0φ(x)(xkX′\n' +
    'n(x))′dx=1\n' +
    '§2n1∫\n' +
    '0φ′(x)xkX′\n' +
    'n(x)dx\n' +
    '=1\n' +
    '§2n1∫\n' +
    '0(φ′(x)xk)′Xn(x)dx=1\n' +
    '§2n1∫\n' +
    '0φ′′(x)xkXn(x)dxk\n' +
    '§2n1∫\n' +
    '0φ′(x)\n' +
    'xxkXn(x)dx:\n' +
    'We denote\n' +
    'φ(2)\n' +
    'n=1∫\n' +
    '0φ′′(x)xkXn(x)dx; φ 1n=1∫\n' +
    '0φ1(x)xkXn(x)dx; φ 1(x) =φ′(x)=x;\n' +
    'and haveφn=1\n' +
    '§2nφ(2)\n' +
    'nk\n' +
    '§2nφ1n. We obtain from the ∟rst integralφ(2)\n' +
    'nby virtue of (8) that\n' +
    'φ(2)\n' +
    'n=1∫\n' +
    '0φ′′(x)xkXn(x)dx=1\n' +
    '§2n1∫\n' +
    '0φ′′(x)(\n' +
    'xkX′\n' +
    'n(x))′\n' +
    'dx\n' +
    'LOBACHEVSKII JOURNAL OF MATHEMATICS8 SABITOV , ZAITSEVA\n' +
    '=1\n' +
    '§2n2\n' +
    '4φ′′(x)xkX′\n' +
    'n(x)♀♀♀1\n' +
    '01∫\n' +
    '0φ′′′(x)xkX′\n' +
    'n(x)dx3\n' +
    '5=1\n' +
    '§2n1∫\n' +
    '0φ′′′(x)xkX′\n' +
    'n(x)dx=φ(3)\n' +
    'n\n' +
    '§2n;\n' +
    'whereφ(3)\n' +
    'n=1∫\n' +
    '0φ′′′(x)xkX′\n' +
    'n(x)dx.\n' +
    'The derivative φ′′′(x)has∟nite variation on segment [0;1]by assumptions of the lemma. Then see\n' +
    '[17] (p. 202) φ(3)\n' +
    'n=O(1)for largen, and, consequently, there is valid the bound jφ(3)\n' +
    'nj ¶C9.\n' +
    'Analogously, we integrate by parts the second integral, and obtain by means of (8) and assumptions\n' +
    'of the lemma\n' +
    'φ1n=1\n' +
    '§2n1∫\n' +
    '0φ1(x)(\n' +
    'xkX′\n' +
    'n(x))′\n' +
    'dx=1\n' +
    '§2n1∫\n' +
    '0φ′\n' +
    '1(x)xkX′\n' +
    'n(x)dx=φ(1)\n' +
    '1n\n' +
    '§2n;\n' +
    'whereφ(1)\n' +
    '1n=1∫\n' +
    '0φ′\n' +
    '1(x)xkX′\n' +
    'n(x)dx, and this integral converges.\n' +
    'We estimate the integral φ(1)\n' +
    '1nfor largenby means of representation\n' +
    'φ(1)\n' +
    '1n=§n\n' +
    'jjeXnjjL2;→(0;1)1∫\n' +
    '0(φ′(x)\n' +
    'x)′\n' +
    'xkx1k\n' +
    '2Jk+1\n' +
    '2(§nx)dx\n' +
    '=§n\n' +
    'jjeXnjjL2;→(0;1)1∫\n' +
    '0x[\n' +
    'φ′′(x)φ′(x)\n' +
    'x]\n' +
    'xk3\n' +
    '2Jk+1\n' +
    '2(§nx)dx:\n' +
    'By assumptions φ′(0) =φ′′(0) = 0 . Therefore, for su ﬃciently small ♫> 0and 0¶x¶♫we have\n' +
    'φ′(x) =φ′(0) +φ′′(0)\n' +
    '1!x+φ′′′(↑x)\n' +
    '2!x2=1\n' +
    '2φ′′′(↑x)x2;0<↑<x;\n' +
    'φ′′(x) =φ′′(0) +φ′′′(↕x)\n' +
    '1!x=φ′′′(↕x)x;0<↕<x:\n' +
    'By virtue of these representations the function\n' +
    'x1\n' +
    '2f(x) =x1\n' +
    '2[\n' +
    'φ′′(x)φ′(x)\n' +
    'x]\n' +
    'xk3\n' +
    '2=[\n' +
    'φ′′(x)φ′(x)\n' +
    'x]\n' +
    'xk\n' +
    '21=[\n' +
    'φ′′′(↕x)1\n' +
    '2φ′′′(↑x)]\n' +
    'xk\n' +
    '2\n' +
    'has bounded variation on segment [0;♫], because it is product of two functions of ∟nite variation see\n' +
    '[17] (p. 202).\n' +
    'One can show analogously that function x1\n' +
    '2f(x)has∟nite variation on segment [♫;1]. Then it has\n' +
    '∟nite variation on segment [0;1]. and, as in the case of integral φ(3)\n' +
    'n, we obtain bound jφ(1)\n' +
    '1nj ¶C10. The\n' +
    '∟rst estimate follows from these estimates.\n' +
    'We integrate by parts twice, and obtain by assumptions of the lemma\n' +
    ' n=1\n' +
    '§2n1∫\n' +
    '0 ′′(x)xkXn(x)dxk\n' +
    '§2n1∫\n' +
    '0 ′(x)\n' +
    'xxkXn(x)dx=1\n' +
    '§2n (2)\n' +
    'nk\n' +
    '§2n 1n;\n' +
    'LOBACHEVSKII JOURNAL OF MATHEMATICSINITIAL-BOUNDARY VALUE PROBLEM 9\n' +
    'where\n' +
    ' (2)\n' +
    'n=1∫\n' +
    '0 ′′(x)xkXn(x)dx;  1n=1∫\n' +
    '0 ′(x)\n' +
    'xxkXn(x)dx:\n' +
    'Analogously, we obtain equalities  (2)\n' +
    'n=O(\n' +
    '§1\n' +
    'n)\n' +
    ', 1n=O(\n' +
    '§1\n' +
    'n)\n' +
    ', which imply by means of  nthe\n' +
    'second bound.\n' +
    'The coe ﬃcients (17) of series (18) under assumptions of the lemma 3 turn into the following ones:\n' +
    'un(t) =φncos§nt+ n\n' +
    '§nsin§nt: (20)\n' +
    'According the Lemmas 1 §3, the series (18) and its derivatives up to the second order inclusive for\n' +
    'any (x;t)2Dallow majoration by the convergent numerical series C111∑\n' +
    'n=1n2;and, consequently,\n' +
    'uniformly converge in the closed domain D. Thus, there is proved\n' +
    'Theorem 2. If functions φ(x)and (x)satisfy assumptions of Lemma 3, and conditions (7)\n' +
    'hold, then there exists a unique solution of problem (2) §(7), it is determined by series (18),\n' +
    'andu(x;t)2C2(D).\n' +
    '4. STABILITY\n' +
    'Theorem 3. The solution of problem (2) §(7) satis ∟es the bound\n' +
    'jjujjL2;→(0;1)¶C12(jjφjjL2;→(0;1)+jj jjL2;→(0;1));\n' +
    'where constant C12does not depend on functions φ(x)and (x).\n' +
    'Proof. By means of (20) and Lemma 1 we have jun(t)j ¶C1(jφnj+j nj=n):We obtain from (18) by\n' +
    'means of this bound\n' +
    'jjujj2\n' +
    'L2;→(0;1)=1∫\n' +
    '0xku2(x;t)dx=1∫\n' +
    '0xk1∑\n' +
    'n=1un(t)Xn(x)1∑\n' +
    'm=1um(t)Xm(x)dx\n' +
    '=1∑\n' +
    'm;n=1un(t)um(t)1∫\n' +
    '0xkXn(x)Xm(x)dx=1∑\n' +
    'n=1u2\n' +
    'n(t)1∫\n' +
    '0xkX2\n' +
    'n(x)dx=1∑\n' +
    'n=1u2\n' +
    'n(t)\n' +
    '¶2C2\n' +
    '11∑\n' +
    'n=1(\n' +
    'jφnj2+1\n' +
    'n2j nj2)\n' +
    '¶2C2\n' +
    '1(1∑\n' +
    'n=1φ2\n' +
    'n+1∑\n' +
    'n=1 2\n' +
    'n)\n' +
    '= 2C2\n' +
    '1(\n' +
    'jjφjj2\n' +
    'L2;→(0;1)+jj jj2\n' +
    'L2;→(0;1))\n' +
    ':\n' +
    'This relation implies this bound.\n' +
    'REFERENCES\n' +
    '1.S. P . Pul\'kin, ►Certain boundary value problems for equations uxx♠uyy+p\n' +
    'xux= 0,◄Uchenye Zapiski\n' +
    'Kuibyshev. gos. ped. inst. 21, 3§55 (1958).\n' +
    '2.K. B. Sabitov and R. R. Il\'yasov, ►Bad-posedness of boundary value problems for a class of hyperbolic\n' +
    'equations, ◄Izvestiya vuzov. Matem. 5, 59§63 (2001).\n' +
    '3.K. B. Sabitov and R. R. Il\'yasov, ►Solving by means of spectral method of the Tricomi problem for an equation\n' +
    'of mixed type with singular coe ﬃcient,◄Izvestiya vuzov. Matem. 2(501), 64 §71 (2004).\n' +
    'LOBACHEVSKII JOURNAL OF MATHEMATICS10 SABITOV , ZAITSEVA\n' +
    '4.R. M. Sa ∟na,►The Keldysh problem for an equation of mixed type of the second kind with Bessel operator, ◄\n' +
    'Diﬀer. uravn. 51(10), 1354 §1366 (2015).\n' +
    '5.N. V . Zaitseva, ►Non-local boundary-value problem for Bhyperbolic equation in rectangular domain, ◄\n' +
    'Vestnik Samar. gos. univ. Ser.: phys.-matem. 20(4), 589 §602 (2016).\n' +
    '6.N. V . Zaitseva, ►Keldysh type problem for Bhyperbolic equation with integral boundary value condition of\n' +
    'the∟rst kind, ◄Lobachevskii J. of Mathematics 38(1), 162 §169 (2017).\n' +
    '7.K. B. Sabitov and N. V . Zaitseva, ►Initial problem for Вhyperbolic equation with integral condition of the\n' +
    'second kind, ◄Diﬀer. uravn. 54(1), 123 §135 (2018).\n' +
    '8.L. S. Pul\'kina, ►Non-local problem with integral condition for hyperbolic equations, ◄Diﬀer. uravn. 40(7),\n' +
    '887§892 (2004).\n' +
    '9.L. S. Pul\'kina, Problems with non-classical conditions for hyperbolic equations (Samara, Samara\n' +
    'University, 2012) [in Russian]\n' +
    '10.L. S. Pul\'kina, ►Boundary value problems for hyperbolic equations with non-local conditions of I and II\n' +
    'kinds, ◄Izvestiya vuzov. Matem. 4, 74§83 (2012).\n' +
    '11.N. I. Yurchuk, ►A mixed problem with integral condition for certain hyperbolic equations, ◄Diﬀer. uravn. 22\n' +
    '(12), 2117 §2126 (1986).\n' +
    '12.A. Bouziani and S. Mesloub, ►A strong solution of an envolution problem with integral condition, ◄Georgian\n' +
    'Mathematical J. 9(12), 149 §159 (2002).\n' +
    '13.S. A. Beilin, ►Existence of solutions for one-dimensional wave equations with nonlocal conditions, ◄Elec-\n' +
    'tronic J. of Di ﬀerential Equations 76, 1§8 (2001).\n' +
    '14.K. B. Sabitov, Equations of mathematical physics (Moscow, Physmathlit, 2013) [in Russian].\n' +
    '15.Ph. Olver, Introduction into asymptotic methods and special functions (Moscow, Mir, 1986) [in\n' +
    'Russian].\n' +
    '16.K. B. Sabitov and E. V . Vagapova, "Dirichlet problem for an equation of mixed type with lines of degeneration\n' +
    'in rectangular domain," Di ﬀer. uravn. 49(1), 68 §78 (2013).\n' +
    '17.I. P . Nathanson, Theory of functions of real variable (3-rd ed., Moscow, Nauka, 1974) [in Russian].\n' +
    'LOBACHEVSKII JOURNAL OF MATHEMATICS\n'